### ISSUE TITLE
Conduct separate experiments where we leave out positive, neutral and negative samples and consider their relative rankings

### ISSUE THREAD

**Issue by Minibrams** [MI-911/cold-start-framework#12]
The pipeline should be able to generate another kind of experiment dataset where, given a cold-start user, we: 
1. Leave out a positive sample 
2. Leave out a neutral sample
3. Leave out a negative sample
4. Shuffle with 100 random unseen samples

Using this, we could then produce a ranking and consider a number of metrics measuring the separation between classes, how often their relative ranking corresponds to the ground truth, etc.

**Comment by bruunand** [comment]
Discuss with supervisors first.

**Comment by bruunand** [comment]
Done.
