### ISSUE TITLE
502 Bad Gateway when downloading ratings

### ISSUE THREAD

**Issue by Minibrams** [MI-911/cold-start-framework#43]
The `scripts/run_download.sh` script throws an error (502 Bad Gateway) when attempting to download ratings from `https://mindreader.tech/api/ratings?versions=100k,100k-newer,100k-fix`. 

The interview scripts will not run. However, we are still able to download the ratings, triples and entities files manually e.g. through a browser.

**Comment by bruunand** [comment]
Cannot reproduce.
