### ISSUE TITLE
Log questions in interview.py

### ISSUE THREAD

**Issue by Minibrams** [MI-911/cold-start-framework#45]
When we are using an interviewer, the interview.py runner should log the questions posed by the interviewer so we can generate an overview over what questions are asked by the interviewers. 

We could be interested in the following: 
1. What entities are asked about most often at each level of the interview (question #1, question #2, etc.)
2. In what sequence do the questions occur? Does the answer to each question matter for the selection of the follow-up question? 
3. How many different entities does an interviewer ask towards?

**Comment by bruunand** [comment]
Done.
